### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by GuiGolfetto** [Rochadevj/love#1]
Quer ser dev ? então bora virar dev. 

Vou deixar aqui umas coisas que vi no seu codebase que são pontos de melhoria
são coisas que desenvolvedores profissionais fazem todos os dias, ta?

(ja aproveita e estuda como subir codigo no git vai branch)

1.  index.html (em todos os arquivos)
- remove todos os espaços entre as linhas

2. https://github.com/Rochadevj/love/blob/dbcf63ce8aaf6d285e679698f54df5650f42f710/acesso/acesso.js#L8 remover comentários do codigo

Caso queria trocar uma ideia sobre carreira e planos de estudos, me acha no linkedin: Guilherme Golfetto

👍🏻

**Comment by Rochadevj** [comment]
fala guilherme, muito obrigado pelas suas dicas! vou arrumar logo logo, sobre seu linkedin nao achei, tem como me adicionar la? acessa henriquerocha.io q la tem meu linkedin

**Comment by Juliacaetanodarosa** [comment]
Oi, estou tentando fazer o mesmo projeto, mas o meu não aparece nada após colocar a senha
Consegue dar alguma dica?

**Comment by Rochadevj** [comment]
ola, me chama no linkedin q vejo para ti, Henrique Rocha
